### ISSUE TITLE
Needs to be built with -fPIC for static linking

### ISSUE THREAD

**Issue by wesm** [conda-forge/glog-feedstock#11]
Google projects don't come set up for position independent code for creating statically-linked shared libraries. See example

https://github.com/conda-forge/gflags-feedstock/blob/master/recipe/build.sh#L6

**Comment by jakirkham** [comment]
A PR for this would be welcome.

**Comment by jakirkham** [comment]
I think this flag is added by default with the new Anaconda compilers. So new builds should already use this. Please let us know if that is not the case.
