### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by wesm** [conda-forge/glog-feedstock#12]
Self-describing

**Comment by jakirkham** [comment]
It’s a good idea and was attempted in PR ( https://github.com/conda-forge/glog-feedstock/pull/8 ). However it requires changes on upstream’s end. It looks like a potential fix was merged upstream. Would be good to verify that the fix works. Then we could either patch the build or wait for an upstream release.

**Comment by xhochy** [comment]
Waiting for an upstream release seems like a possible long wait, not sure whether `glog` also switched to a `live at head` mode like abseil or just has not enough people maintaining it.

**Comment by wesm** [comment]
Google seems ambivalent about making releases so we should consider moving to dated releases similar to re2 and some other projects

**Comment by xhochy** [comment]
Can we do this in a non-destructive fashion? Using dated-releases with a version lower than `0.3.6` so that we can use this when this ever is released. What about `0.3.5.post20181209`?

**Comment by jakirkham** [comment]
I asked them about this a while ago and recall they were not ready to make the release as there are some breaking changes in `master` and more breaking changes planned. They wanted to finish these before making a release. So I’d be a little hesitant to roll our own release. Is our only interest in this to get a Windows build? If so, maybe we can try vendoring their `CMakeLists.txt` and adjust it as needed.

**Comment by jakirkham** [comment]
Should add I had done some work on this in PR ( https://github.com/conda-forge/glog-feedstock/pull/8 ). Looking at it, we may be able to just apply a few patches from upstream to get it to work.

**Comment by cboulay** [comment]
+1

I'm trying to get ceres-solver to work and it installs but some of its dependencies are static libs instead of dlls. See the issue [here](https://github.com/conda-forge/ceres-solver-feedstock/issues/3). I was told by its maintainer that I must use the conda-forge channel for glog, but this does not exist for Windows.

**Comment by jschueller** [comment]
I think #16 is ready, it did not build on vc9 and I skipped one failing test, hopefully someone would want to go further from that.
