### ISSUE TITLE
Testing new release (0.4.0)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/glog-feedstock#14]
Looks like the glog team is about to cut a new release. ( https://github.com/google/glog/pull/419 ) As it has been a while since they last released and there are a lot of changes, we should try building it and testing it so we can give them feedback before they release.

**Comment by jakirkham** [comment]
cc @wesm (in case it is of interest)

**Comment by wesm** [comment]
I'm a bit bandwidth poor right now, @xhochy @pitrou or @kszucs any interest in testing out glog 0.4.0? Our use of glog in Apache Arrow is pretty minimal

**Comment by jakirkham** [comment]
Closing as we have built the release ( https://github.com/conda-forge/glog-feedstock/pull/15 ). Some patches are being upstreamed from that.
